In [102]:
import pandas as pd
import numpy as np

In [103]:
df = pd.read_csv("GroceryDataset.csv")

In [104]:
df.head()

,Sub Category,Price,Discount,Rating,Title,Currency,Feature,Product Description
0,Bakery & Desserts,$56.99,No Discount,Rated 4.3 out of 5 stars based on 265 reviews.,"David’s Cookies Mile High Peanut Butter Cake, ...",$,"""10"""" Peanut Butter Cake\nCertified Kosher OU-...",A cake the dessert epicure will die for!Our To...
1,Bakery & Desserts,$159.99,No Discount,Rated 5 out of 5 stars based on 1 reviews.,"The Cake Bake Shop 8"" Round Carrot Cake (16-22...",$,Spiced Carrot Cake with Cream Cheese Frosting ...,"Due to the perishable nature of this item, ord..."
2,Bakery & Desserts,$44.99,No Discount,Rated 4.1 out of 5 stars based on 441 reviews.,"St Michel Madeleine, Classic French Sponge Cak...",$,100 count\nIndividually wrapped\nMade in and I...,Moist and buttery sponge cakes with the tradit...
3,Bakery & Desserts,$39.99,No Discount,Rated 4.7 out of 5 stars based on 9459 reviews.,"David's Cookies Butter Pecan Meltaways 32 oz, ...",$,Butter Pecan Meltaways\n32 oz 2-Pack\nNo Prese...,These delectable butter pecan meltaways are th...
4,Bakery & Desserts,$59.99,No Discount,Rated 4.5 out of 5 stars based on 758 reviews.,"David’s Cookies Premier Chocolate Cake, 7.2 lb...",$,"""10"" Four Layer Chocolate Cake\nCertified Kosh...",A cake the dessert epicure will die for!To the...

In [105]:
df.columns

Index(['Sub Category', 'Price', 'Discount', 'Rating', 'Title', 'Currency',
       'Feature', 'Product Description'],
      dtype='object')

In [106]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1757 entries, 0 to 1756
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Sub Category         1757 non-null   object
 1   Price                1754 non-null   object
 2   Discount             1757 non-null   object
 3   Rating               682 non-null    object
 4   Title                1757 non-null   object
 5   Currency             1752 non-null   object
 6   Feature              1739 non-null   object
 7   Product Description  1715 non-null   object
dtypes: object(8)
memory usage: 109.9+ KB

In [107]:
df.describe

<bound method NDFrame.describe of            Sub Category     Price     Discount  \
0     Bakery & Desserts   $56.99   No Discount
1     Bakery & Desserts  $159.99   No Discount
2     Bakery & Desserts   $44.99   No Discount
3     Bakery & Desserts   $39.99   No Discount
4     Bakery & Desserts   $59.99   No Discount
...                 ...       ...          ...
1752             Snacks   $23.99   No Discount
1753             Snacks   $49.99   No Discount
1754             Snacks   $22.99   No Discount
1755             Snacks   $17.49   No Discount
1756             Snacks   $21.99   No Discount

                                               Rating  \
0      Rated 4.3 out of 5 stars based on 265 reviews.
1          Rated 5 out of 5 stars based on 1 reviews.
2      Rated 4.1 out of 5 stars based on 441 reviews.
3     Rated 4.7 out of 5 stars based on 9459 reviews.
4      Rated 4.5 out of 5 stars based on 758 reviews.
...                                               ...
1752                                              NaN
1753                                              NaN
1754                                              NaN
1755                                              NaN
1756                                              NaN

                                                  Title Currency  \
0     David’s Cookies Mile High Peanut Butter Cake, ...        $
1     The Cake Bake Shop 8" Round Carrot Cake (16-22...        $
2     St Michel Madeleine, Classic French Sponge Cak...        $
3     David's Cookies Butter Pecan Meltaways 32 oz, ...        $
4     David’s Cookies Premier Chocolate Cake, 7.2 lb...        $
...                                                 ...      ...
1752  Oberto Thin Style Smoked Sausage Stick, Cockta...        $
1753        Cheetos Crunchy, Original, 2.1 oz, 64-count        $
1754  Sabritas Chile & Limon Mix, Variety Pack, 30-c...        $
1755             Fruit Roll-Ups, Variety Pack, 72-count        $
1756  Takis, Rolled Tortilla Chips, Intense Nacho, 1...        $

                                                Feature  \
0     "10"" Peanut Butter Cake\nCertified Kosher OU-...
1     Spiced Carrot Cake with Cream Cheese Frosting ...
2     100 count\nIndividually wrapped\nMade in and I...
3     Butter Pecan Meltaways\n32 oz 2-Pack\nNo Prese...
4     "10" Four Layer Chocolate Cake\nCertified Kosh...
...                                                 ...
1752  Cocktail Pepperoni   Smoked Sausage Sticks   3...
1753                              Made with Real Cheese
1754  Chile & Limón Mix   Variety Pack   30 ct   Net...
1755  Variety Pack   1   Box with 72 Rolls   Flavore...
1756  Intense Nacho Cheese   Non-Spicy   1 oz bag, 5...

                                    Product Description
0     A cake the dessert epicure will die for!Our To...
1     Due to the perishable nature of this item, ord...
2     Moist and buttery sponge cakes with the tradit...
3     These delectable butter pecan meltaways are th...
4     A cake the dessert epicure will die for!To the...
...                                                 ...
1752  Cocktail PepperoniSmoked Sausage Sticks3 oz ba...
1753                                64-count2.1 oz Bags
1754  8-Doritos Dinamita Chile Limón Flavored Rolled...
1755  Fruit Flavored Snacks\nVariety Includes: Straw...
1756  Takis Non-Spicy Cheese Tortilla Chips\nIndivid...

[1757 rows x 8 columns]>

In [108]:
df.isnull().sum()

Sub Category              0
Price                     3
Discount                  0
Rating                 1075
Title                     0
Currency                  5
Feature                  18
Product Description      42
dtype: int64

In [109]:
df['Rating'].value_counts()

Rating
No Reviews                                        61
Rated 5 out of 5 stars based on 1 reviews.         5
Rated 5 out of 5 stars based on 2 reviews.         5
Rated 4.2 out of 5 stars based on 104 reviews.     4
Rated 4.5 out of 5 stars based on 26 reviews.      4
                                                  ..
Rated 4.3 out of 5 stars based on 117 reviews.     1
Rated 4.6 out of 5 stars based on 556 reviews.     1
Rated 4 out of 5 stars based on 128 reviews.       1
Rated 4.5 out of 5 stars based on 454 reviews.     1
Rated 4.7 out of 5 stars based on 64 reviews.      1
Name: count, Length: 483, dtype: int64

In [110]:
df['Currency'].value_counts()

Currency
$    1752
Name: count, dtype: int64

In [111]:
df['Currency'] = 1

In [112]:
df['Price'] = df['Price'].str.extract(r'([\d\.]+)').astype(float)
df['Price']

0        56.99
1       159.99
2        44.99
3        39.99
4        59.99
         ...
1752     23.99
1753     49.99
1754     22.99
1755     17.49
1756     21.99
Name: Price, Length: 1757, dtype: float64

In [113]:
df['Price'].dtype

dtype('float64')

In [114]:
df['Discount'].value_counts()

Discount
No Discount                                                                                                   1626
After $5 OFF                                                                                                    13
After $6 OFF                                                                                                    13
After $4 OFF                                                                                                    12
After $3 OFF                                                                                                    11
After $3.30 OFF                                                                                                  7
After $3.80 OFF                                                                                                  7
After $3.60 OFF                                                                                                  6
After $30 OFF                                                                                                    4
After $20 OFF                                                                                                    4
After $3.50 OFF                                                                                                  4
After $50 OFF                                                                                                    4
After $3.10 OFF                                                                                                  3
After $60 OFF                                                                                                    3
After $10 OFF                                                                                                    3
After $2.20 OFF                                                                                                  3
After $2.50 OFF                                                                                                  2
After $12 OFF                                                                                                    2
After $2.30 OFF                                                                                                  2
After $40 OFF                                                                                                    2
After $2.40 OFF                                                                                                  2
After $5.60 OFF                                                                                                  2
After $70 OFF                                                                                                    2
.                                                                                                                2
This item is not returnable.                                                                                     1
After $4.50 OFF                                                                                                  1
After $8 OFF                                                                                                     1
After $2.80 OFF                                                                                                  1
After $1.50 OFF                                                                                                  1
After $9.30 OFF                                                                                                  1
After $2.70 OFF                                                                                                  1
After $40 - $70 OFF                                                                                              1
After $80 OFF                                                                                                    1
After $40 - $80 OFF                                                                                              1
Limit 5 Per Member                                                                                               1
Limit 1 Per Member                                                                                               1
After $2.60 OFF                                                                                                  1
After $6.50 OFF                                                                                                  1
After $7 OFF                                                                                                     1
Costco Members Receive an Additional $5 OFF Caramel Peanut Protein Bars with FitCrunch through Costco Next       1
After $4.10 OFF                                                                                                  1
After $2 OFF                                                                                                     1
Name: count, dtype: int64

In [115]:
df['Discount_value']=df['Discount'].str.extract(r'\$?(\d+\.?\d*)').astype(float)

In [116]:
df.drop(columns=['Discount'],inplace=True)
df

,Sub Category,Price,Rating,Title,Currency,Feature,Product Description,Discount_value
0,Bakery & Desserts,56.99,Rated 4.3 out of 5 stars based on 265 reviews.,"David’s Cookies Mile High Peanut Butter Cake, ...",1,"""10"""" Peanut Butter Cake\nCertified Kosher OU-...",A cake the dessert epicure will die for!Our To...,NaN
1,Bakery & Desserts,159.99,Rated 5 out of 5 stars based on 1 reviews.,"The Cake Bake Shop 8"" Round Carrot Cake (16-22...",1,Spiced Carrot Cake with Cream Cheese Frosting ...,"Due to the perishable nature of this item, ord...",NaN
2,Bakery & Desserts,44.99,Rated 4.1 out of 5 stars based on 441 reviews.,"St Michel Madeleine, Classic French Sponge Cak...",1,100 count\nIndividually wrapped\nMade in and I...,Moist and buttery sponge cakes with the tradit...,NaN
3,Bakery & Desserts,39.99,Rated 4.7 out of 5 stars based on 9459 reviews.,"David's Cookies Butter Pecan Meltaways 32 oz, ...",1,Butter Pecan Meltaways\n32 oz 2-Pack\nNo Prese...,These delectable butter pecan meltaways are th...,NaN
4,Bakery & Desserts,59.99,Rated 4.5 out of 5 stars based on 758 reviews.,"David’s Cookies Premier Chocolate Cake, 7.2 lb...",1,"""10"" Four Layer Chocolate Cake\nCertified Kosh...",A cake the dessert epicure will die for!To the...,NaN
...,...,...,...,...,...,...,...,...
1752,Snacks,23.99,NaN,"Oberto Thin Style Smoked Sausage Stick, Cockta...",1,Cocktail Pepperoni Smoked Sausage Sticks 3...,Cocktail PepperoniSmoked Sausage Sticks3 oz ba...,NaN
1753,Snacks,49.99,NaN,"Cheetos Crunchy, Original, 2.1 oz, 64-count",1,Made with Real Cheese,64-count2.1 oz Bags,NaN
1754,Snacks,22.99,NaN,"Sabritas Chile & Limon Mix, Variety Pack, 30-c...",1,Chile & Limón Mix Variety Pack 30 ct Net...,8-Doritos Dinamita Chile Limón Flavored Rolled...,NaN
1755,Snacks,17.49,NaN,"Fruit Roll-Ups, Variety Pack, 72-count",1,Variety Pack 1 Box with 72 Rolls Flavore...,Fruit Flavored Snacks\nVariety Includes: Straw...,NaN
1756,Snacks,21.99,NaN,"Takis, Rolled Tortilla Chips, Intense Nacho, 1...",1,"Intense Nacho Cheese Non-Spicy 1 oz bag, 5...",Takis Non-Spicy Cheese Tortilla Chips\nIndivid...,NaN

In [117]:
df.drop(columns=['Currency'],inplace=True)
df

,Sub Category,Price,Rating,Title,Feature,Product Description,Discount_value
0,Bakery & Desserts,56.99,Rated 4.3 out of 5 stars based on 265 reviews.,"David’s Cookies Mile High Peanut Butter Cake, ...","""10"""" Peanut Butter Cake\nCertified Kosher OU-...",A cake the dessert epicure will die for!Our To...,NaN
1,Bakery & Desserts,159.99,Rated 5 out of 5 stars based on 1 reviews.,"The Cake Bake Shop 8"" Round Carrot Cake (16-22...",Spiced Carrot Cake with Cream Cheese Frosting ...,"Due to the perishable nature of this item, ord...",NaN
2,Bakery & Desserts,44.99,Rated 4.1 out of 5 stars based on 441 reviews.,"St Michel Madeleine, Classic French Sponge Cak...",100 count\nIndividually wrapped\nMade in and I...,Moist and buttery sponge cakes with the tradit...,NaN
3,Bakery & Desserts,39.99,Rated 4.7 out of 5 stars based on 9459 reviews.,"David's Cookies Butter Pecan Meltaways 32 oz, ...",Butter Pecan Meltaways\n32 oz 2-Pack\nNo Prese...,These delectable butter pecan meltaways are th...,NaN
4,Bakery & Desserts,59.99,Rated 4.5 out of 5 stars based on 758 reviews.,"David’s Cookies Premier Chocolate Cake, 7.2 lb...","""10"" Four Layer Chocolate Cake\nCertified Kosh...",A cake the dessert epicure will die for!To the...,NaN
...,...,...,...,...,...,...,...
1752,Snacks,23.99,NaN,"Oberto Thin Style Smoked Sausage Stick, Cockta...",Cocktail Pepperoni Smoked Sausage Sticks 3...,Cocktail PepperoniSmoked Sausage Sticks3 oz ba...,NaN
1753,Snacks,49.99,NaN,"Cheetos Crunchy, Original, 2.1 oz, 64-count",Made with Real Cheese,64-count2.1 oz Bags,NaN
1754,Snacks,22.99,NaN,"Sabritas Chile & Limon Mix, Variety Pack, 30-c...",Chile & Limón Mix Variety Pack 30 ct Net...,8-Doritos Dinamita Chile Limón Flavored Rolled...,NaN
1755,Snacks,17.49,NaN,"Fruit Roll-Ups, Variety Pack, 72-count",Variety Pack 1 Box with 72 Rolls Flavore...,Fruit Flavored Snacks\nVariety Includes: Straw...,NaN
1756,Snacks,21.99,NaN,"Takis, Rolled Tortilla Chips, Intense Nacho, 1...","Intense Nacho Cheese Non-Spicy 1 oz bag, 5...",Takis Non-Spicy Cheese Tortilla Chips\nIndivid...,NaN

In [118]:
print(df['Rating'].str.startswith("Rated").sum())
print(df['Rating'].count())
print("Missing Reviews:", df[df["Rating"]==None])

617
682
Missing Reviews: Empty DataFrame
Columns: [Sub Category, Price, Rating, Title, Feature, Product Description, Discount_value]
Index: []

In [119]:
df.drop(columns=['Discount_value'],inplace=True)
df

,Sub Category,Price,Rating,Title,Feature,Product Description
0,Bakery & Desserts,56.99,Rated 4.3 out of 5 stars based on 265 reviews.,"David’s Cookies Mile High Peanut Butter Cake, ...","""10"""" Peanut Butter Cake\nCertified Kosher OU-...",A cake the dessert epicure will die for!Our To...
1,Bakery & Desserts,159.99,Rated 5 out of 5 stars based on 1 reviews.,"The Cake Bake Shop 8"" Round Carrot Cake (16-22...",Spiced Carrot Cake with Cream Cheese Frosting ...,"Due to the perishable nature of this item, ord..."
2,Bakery & Desserts,44.99,Rated 4.1 out of 5 stars based on 441 reviews.,"St Michel Madeleine, Classic French Sponge Cak...",100 count\nIndividually wrapped\nMade in and I...,Moist and buttery sponge cakes with the tradit...
3,Bakery & Desserts,39.99,Rated 4.7 out of 5 stars based on 9459 reviews.,"David's Cookies Butter Pecan Meltaways 32 oz, ...",Butter Pecan Meltaways\n32 oz 2-Pack\nNo Prese...,These delectable butter pecan meltaways are th...
4,Bakery & Desserts,59.99,Rated 4.5 out of 5 stars based on 758 reviews.,"David’s Cookies Premier Chocolate Cake, 7.2 lb...","""10"" Four Layer Chocolate Cake\nCertified Kosh...",A cake the dessert epicure will die for!To the...
...,...,...,...,...,...,...
1752,Snacks,23.99,NaN,"Oberto Thin Style Smoked Sausage Stick, Cockta...",Cocktail Pepperoni Smoked Sausage Sticks 3...,Cocktail PepperoniSmoked Sausage Sticks3 oz ba...
1753,Snacks,49.99,NaN,"Cheetos Crunchy, Original, 2.1 oz, 64-count",Made with Real Cheese,64-count2.1 oz Bags
1754,Snacks,22.99,NaN,"Sabritas Chile & Limon Mix, Variety Pack, 30-c...",Chile & Limón Mix Variety Pack 30 ct Net...,8-Doritos Dinamita Chile Limón Flavored Rolled...
1755,Snacks,17.49,NaN,"Fruit Roll-Ups, Variety Pack, 72-count",Variety Pack 1 Box with 72 Rolls Flavore...,Fruit Flavored Snacks\nVariety Includes: Straw...
1756,Snacks,21.99,NaN,"Takis, Rolled Tortilla Chips, Intense Nacho, 1...","Intense Nacho Cheese Non-Spicy 1 oz bag, 5...",Takis Non-Spicy Cheese Tortilla Chips\nIndivid...

In [120]:
# Extract rating and total reviews using regex
df[['Rating_Value', 'Total_Reviews']] = df['Rating'].str.extract(r'Rated (\d+\.?\d*) out of 5.*?based on (\d+)')

# Convert to appropriate types
df['Rating_Value'] = df['Rating_Value'].astype(float)
df['Total_Reviews'] = df['Total_Reviews'].astype(float)

In [121]:
df['Sub Category'].value_counts()

Sub Category
Snacks                          293
Pantry & Dry Goods              171
Candy                           154
Beverages & Water               148
Meat & Seafood                  144
Kirkland Signature Grocery      122
Coffee                           95
Cleaning Supplies                94
Gift Baskets                     89
Paper & Plastic Products         88
Household                        81
Floral                           75
Seafood                          47
Laundry Detergent & Supplies     39
Bakery & Desserts                33
Organic                          33
Breakfast                        21
Deli                             21
Poultry                           9
Name: count, dtype: int64

In [122]:
df.groupby(['Sub Category'])['Rating'].apply(lambda x: x.isna().sum())

Sub Category
Bakery & Desserts                 0
Beverages & Water               124
Breakfast                        19
Candy                           131
Cleaning Supplies                55
Coffee                           57
Deli                              1
Floral                            0
Gift Baskets                      5
Household                        81
Kirkland Signature Grocery      103
Laundry Detergent & Supplies     22
Meat & Seafood                    1
Organic                          25
Pantry & Dry Goods              126
Paper & Plastic Products         72
Poultry                           0
Seafood                           1
Snacks                          252
Name: Rating, dtype: int64

In [123]:
df.drop(columns=['Rating'],inplace=True)
df

,Sub Category,Price,Title,Feature,Product Description,Rating_Value,Total_Reviews
0,Bakery & Desserts,56.99,"David’s Cookies Mile High Peanut Butter Cake, ...","""10"""" Peanut Butter Cake\nCertified Kosher OU-...",A cake the dessert epicure will die for!Our To...,4.3,265.0
1,Bakery & Desserts,159.99,"The Cake Bake Shop 8"" Round Carrot Cake (16-22...",Spiced Carrot Cake with Cream Cheese Frosting ...,"Due to the perishable nature of this item, ord...",5.0,1.0
2,Bakery & Desserts,44.99,"St Michel Madeleine, Classic French Sponge Cak...",100 count\nIndividually wrapped\nMade in and I...,Moist and buttery sponge cakes with the tradit...,4.1,441.0
3,Bakery & Desserts,39.99,"David's Cookies Butter Pecan Meltaways 32 oz, ...",Butter Pecan Meltaways\n32 oz 2-Pack\nNo Prese...,These delectable butter pecan meltaways are th...,4.7,9459.0
4,Bakery & Desserts,59.99,"David’s Cookies Premier Chocolate Cake, 7.2 lb...","""10"" Four Layer Chocolate Cake\nCertified Kosh...",A cake the dessert epicure will die for!To the...,4.5,758.0
...,...,...,...,...,...,...,...
1752,Snacks,23.99,"Oberto Thin Style Smoked Sausage Stick, Cockta...",Cocktail Pepperoni Smoked Sausage Sticks 3...,Cocktail PepperoniSmoked Sausage Sticks3 oz ba...,NaN,NaN
1753,Snacks,49.99,"Cheetos Crunchy, Original, 2.1 oz, 64-count",Made with Real Cheese,64-count2.1 oz Bags,NaN,NaN
1754,Snacks,22.99,"Sabritas Chile & Limon Mix, Variety Pack, 30-c...",Chile & Limón Mix Variety Pack 30 ct Net...,8-Doritos Dinamita Chile Limón Flavored Rolled...,NaN,NaN
1755,Snacks,17.49,"Fruit Roll-Ups, Variety Pack, 72-count",Variety Pack 1 Box with 72 Rolls Flavore...,Fruit Flavored Snacks\nVariety Includes: Straw...,NaN,NaN
1756,Snacks,21.99,"Takis, Rolled Tortilla Chips, Intense Nacho, 1...","Intense Nacho Cheese Non-Spicy 1 oz bag, 5...",Takis Non-Spicy Cheese Tortilla Chips\nIndivid...,NaN,NaN

In [125]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [127]:
df['Sub Category Encoded'] = le.fit_transform(df['Sub Category'])
df['Sub Category Encoded'].value_counts()

Sub Category Encoded
18    293
14    171
3     154
1     148
12    144
10    122
5      95
4      94
8      89
15     88
9      81
7      75
17     47
11     39
0      33
13     33
2      21
6      21
16      9
Name: count, dtype: int64

In [128]:
df

,Sub Category,Price,Title,Feature,Product Description,Rating_Value,Total_Reviews,Sub Category Encoded
0,Bakery & Desserts,56.99,"David’s Cookies Mile High Peanut Butter Cake, ...","""10"""" Peanut Butter Cake\nCertified Kosher OU-...",A cake the dessert epicure will die for!Our To...,4.3,265.0,0
1,Bakery & Desserts,159.99,"The Cake Bake Shop 8"" Round Carrot Cake (16-22...",Spiced Carrot Cake with Cream Cheese Frosting ...,"Due to the perishable nature of this item, ord...",5.0,1.0,0
2,Bakery & Desserts,44.99,"St Michel Madeleine, Classic French Sponge Cak...",100 count\nIndividually wrapped\nMade in and I...,Moist and buttery sponge cakes with the tradit...,4.1,441.0,0
3,Bakery & Desserts,39.99,"David's Cookies Butter Pecan Meltaways 32 oz, ...",Butter Pecan Meltaways\n32 oz 2-Pack\nNo Prese...,These delectable butter pecan meltaways are th...,4.7,9459.0,0
4,Bakery & Desserts,59.99,"David’s Cookies Premier Chocolate Cake, 7.2 lb...","""10"" Four Layer Chocolate Cake\nCertified Kosh...",A cake the dessert epicure will die for!To the...,4.5,758.0,0
...,...,...,...,...,...,...,...,...
1752,Snacks,23.99,"Oberto Thin Style Smoked Sausage Stick, Cockta...",Cocktail Pepperoni Smoked Sausage Sticks 3...,Cocktail PepperoniSmoked Sausage Sticks3 oz ba...,NaN,NaN,18
1753,Snacks,49.99,"Cheetos Crunchy, Original, 2.1 oz, 64-count",Made with Real Cheese,64-count2.1 oz Bags,NaN,NaN,18
1754,Snacks,22.99,"Sabritas Chile & Limon Mix, Variety Pack, 30-c...",Chile & Limón Mix Variety Pack 30 ct Net...,8-Doritos Dinamita Chile Limón Flavored Rolled...,NaN,NaN,18
1755,Snacks,17.49,"Fruit Roll-Ups, Variety Pack, 72-count",Variety Pack 1 Box with 72 Rolls Flavore...,Fruit Flavored Snacks\nVariety Includes: Straw...,NaN,NaN,18
1756,Snacks,21.99,"Takis, Rolled Tortilla Chips, Intense Nacho, 1...","Intense Nacho Cheese Non-Spicy 1 oz bag, 5...",Takis Non-Spicy Cheese Tortilla Chips\nIndivid...,NaN,NaN,18

In [ ]:
print(df['Feature'])